### ISSUE TITLE
Sort node search results more cleverly

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Gamma/qgraph#176] opened 2021-04-07 15:36 UTC
For example, when we search for "pheno", I'd like "phenotypic feature" to be the first result, rather than "set of phenotypic features" or "disease or phenotypic feature". Sorting the results by length might be sufficient.

**Comment by maximusunc** [comment] 2021-07-08 19:01
Duplicate of #99

**Closed by maximusunc** 2021-07-08 19:01 UTC
